name: Pull Request Checks

on:
  pull_request:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Type check
      run: npm run typecheck
    
    - name: Lint
      run: npm run lint:check
    
    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Security audit
      run: npm audit --omit=dev --audit-level moderate

  size-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build and check bundle size
      run: |
        npm run build
        du -sh dist/
        echo "Bundle size check completed"