name: Security Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run security audit every Monday at 6 AM UTC
    - cron: '0 6 * * 1'

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Production security audit
      run: |
        echo "🔍 Scanning production dependencies for vulnerabilities..."
        npm audit --omit=dev --audit-level moderate
      
    - name: Development security audit (informational)
      run: |
        echo "ℹ️  Scanning development dependencies (informational only)..."
        npm audit --audit-level moderate || echo "⚠️  Development dependency vulnerabilities detected (non-blocking)"
      continue-on-error: true

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate